auctions/urls.py
from django.urls import path

from . import views

app_name = 'auctions'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('myauctions/', views.my_auctions, name='my_auctions'),
    # Example: /auctions/
    path('', views.auctions, name='auctions'),
    # Example: /auctions/5/
    path('<int:auction_id>/', views.detail, name='detail'),
    # Example: /auctions/5/results/
    # path('<int:auction_id>/results/', views.results, name='results'),
    # Example: /auctions/5/bid/
    path('<int:auction_id>/bid/', views.bid, name='bid'),
    path('my_bids/', views.my_bids, name="my_bids"),
    path('marketplace/', views.marketplace, name="marketplace"),
    path('collections/', views.collections, name="collections"),
    path('add_collection/', views.add_collection, name="add_collection"),
    path('contact/', views.contact, name="contact"),
    path('creators/', views.creators, name="creators"),
    path('deposit/', views.deposit, name="deposit"),
    path('withdraw/', views.withdraw, name="withdraw"),
    # path('process-payment/', views.process_payment, name='process_payment'),
]

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home')
]

nft_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auctions.urls')),
    path('accounts/', include('accounts.urls')),
    path('auctions/', include('auctions.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/_alerts.html
{% if messages %}
  {% for message in messages %}
    <div id="message" class="container">
      <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
        <strong>
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error: 
          {% else %}
            {{ message.tags|title }}
          {% endif %}
        </strong>
        {{ message }}
      </div>
    </div>
  {% endfor %}
{% endif %}

templates/partials/_footer.html
{% load static %}
{% load static %}
<footer class="footer__1">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 space-y-20">
                <div class="footer__logo">
                    <a href="index.html">
                        <img src="{% static 'img/logos/Logo.png' %}" alt="logo" id="logo_js_f">
                    </a>
                </div>
                <p class="footer__text">
                    Nft Pro is a shared liquidity NFT market smart contract
                </p>
                <div>
                    <ul class="footer__social space-x-10 mb-40">
                        <li><a href="https://facebook.com"> <i class="ri-facebook-line"></i> </a>
                        </li>
                        <li><a href="https://messenger.com"> <i class="ri-messenger-line"></i> </a>
                        </li>
                        <li><a href="https://whatsapp.com"> <i class="ri-whatsapp-line"></i> </a>
                        </li>
                        <li><a href="https://youtube.com"> <i class="ri-youtube-line"></i> </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-6">
                <h6 class="footer__title">Nft Pro</h6>
                <ul class="footer__list">
                    <li><a href="#"> Collections </a></li>
                    <li><a href="#"> Contact</a></li> </a>
                </ul>
            </div>
            <div class="col-lg-2 col-6">
                <h6 class="footer__title">Assets</h6>
                <ul class="footer__list">
                    <li><a href="#"> Profile </a>
                    </li>
                    <li><a href="#"> Creators </a>
                    </li>
                    <li><a href="#"> Colletctions </a>
                    </li>
                </ul>
            </div>
            <div class="col-lg-2 col-6">
                <h6 class="footer__title">Company</h6>
                <ul class="footer__list">
                    <li><a href="#"> About Us </a>
                    </li>
                    <li><a href="#"> Upload </a></li>
                    <li><a href="#"> Item details </a>
                    </li>
                </ul>
            </div>
        </div>
        <p class="copyright text-center">
            Copyright © 2022. NFT PRO.
        </p>

    </div>
</footer>
<script type="text/javascript">
var n1 = document.getElementById("num1");
var n2 = document.getElementById("num2");
var res = document.getElementById("result");

document.getElementById("div").addEventListener("click", function() {
res.value = parseInt(n1.value)/parseInt(n2.value);
});
</script>
	<script>
			    $(".dark").on('click', function (e) {

				document.getElementById("img_js").src = "{% static 'img/bg/in_hero1_dark.png' %}"


			});
			$(".light").on('click', function (e) {
				document.getElementById("img_js").src = "{% static 'img/bg/in_hero1.png' %}"
			});
			</script>
		<!-- 🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈 SCRIPTS -->
		<script src="{% static 'js/jquery-3.6.0.js' %}"></script>
		<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
		<script src="{% static 'js/swiper-bundle.min.js' %}"></script>
		<script src="{% static 'js/gsap.min.js' %}"></script>
		<script src="{% static 'js/ScrollTrigger.min.js' %}"></script>
		<script src="{% static 'js/sticky-sidebar.js' %}"></script>
		<script src="{% static 'js/script.js' %}"></script>
		<script src="{% static 'js/web3.min.js' %}"></script>
		<script src="{% static 'js/moralis.js' %}"></script>
		<script src="{% static 'js/nft.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
		<script src="{% static 'js/lottie-player.js' %}"></script>

templates/partials/_navbar.html
{% load static %}
<header class="header__1 js-header" id="header">
    <div class="container">
        <div class="wrapper js-header-wrapper">
            <div class="header__logo ml-30">
                <a href="/">
                    <img
                            class="header__logo"
                            id="logo_js"
                            src="{% static 'img/logos/Logo.png' %}"
                            alt="logo"
                    />
                </a>
            </div>

            <!-- ==================  -->
            <div class="header__menu">
                <ul class="d-flex space-x-20">
                    <li>
                        <a class="color_black" href="{% url 'auctions:index' %}"> Home</a>
                    </li>
                    <li>
                        <a class="color_black" href="{% url 'auctions:marketplace' %}"> Marketplace</a>
                    </li>
                    <li>
                        <a class="color_black" href="{% url 'auctions:creators' %}"> Creators</a>
                    </li>
                    <li>
                        <a class="color_black" href="{% url 'auctions:collections' %}"> Collections</a>
                    </li>
                    <li>
                        <a class="color_black" href="{% url 'auctions:contact' %}"> Contact</a>
                    </li>
                    <!--<li class="has_popup2">
                        <a class="color_black is_new" href="#">Pages <i class="ri-more-2-fill"></i></a>
                        <ul class="menu__popup2 space-y-20">
                            <div class="row sub_menu_row">

                                <div class="col-lg-6 space-y-10">

                                    <li>
                                        <a href="Item-details.html">
                                            <i class="ri-gallery-line"></i>
                                            Item details
                                        </a>
                                    </li>

                                    <li>
                                        <a class="is_new" href="ranking.html">
                                            <i class="ri-funds-line"></i>
                                            Ranking
                                        </a>
                                    </li>

                                </div>
                                <div class="col-lg-6 space-y-10">


                                    <li>
                                        <a href="Connect-wallet.html">
                                            <i class="ri-wallet-3-line"></i>
                                            Connect wallet
                                        </a>
                                    </li>


                                    <li>
                                        <a href="questions.html">
                                            <i class="ri-question-line"></i>
                                            FAQ
                                        </a>
                                    </li>

                                </div>
                            </div>
                        </ul>
                    </li>-->
                </ul>
            </div>
            <!-- ================= -->
            <div class="header__search">
                <input type="text" placeholder="Search"/>
                <button class="header__result">
                    <i class="ri-search-line"></i>
                </button>
            </div>
            {% if user.is_authenticated %}
            <div class="header__btns">
                <a class="btn btn-primary btn-sm" href="{% url 'auctions:create' %}">Create</a>
            </div>
            <div class="d-flex align-items-center space-x-20">
                <div class="header__notifications">
                    <div class="header__btns">
                        <a href="#" id="connectbtn">
                            <img width="45" src="{% static 'img/icons/metamask.svg' %}" alt="">
                        </a>
                    </div>
                </div>
                <div class="header__avatar">
                    <div class="price">
                        <span><strong>$ {{user.userprofile.current_balance}} </strong> </span>
                    </div>
                    <img
                            class="avatar"
                            src="{{user.userprofile.profile_photo.url}}"
                            alt="avatar"
                    />
                    <div class="avatar_popup space-y-20">
                        <div class="d-flex align-items-center justify-content-between">
                            <span> {{ user.first_name }} {{ user.last_name }}</span>
                        </div>
                        <div class="d-flex align-items-center space-x-10">
                            <p class="text-lg font-book text-green-400">Balance</p>

                            <div class="info">
                                <p class="w-full text-sm font-bold text-green-500">
                                    <strong>{{user.userprofile.current_balance}} USD</strong>
                                </p>
                                <div class="hr"></div>
                                <p class="w-full text-sm font-bold text-green-500">
                                    <strong>0.906 ETH</strong>
                                </p>
                            </div>

                        </div>
                        <div class="hr"></div>
                        <div class="links space-y-10">
                            <a href="{% url 'dashboard' %}">
                                <i class="ri-landscape-line"></i> <span> Dashboard</span>
                            </a>
                            <a href="{% url 'auctions:add_collection' %}">
                                <i class="ri-pencil-line"></i> <span> Add Collection</span>
                            </a>
                            <a href="{% url 'auctions:my_bids' %}">
                                <i class="ri-user-line"></i> <span> My items</span>
                            </a>
                            <!--<a href="#">
                                <i class="ri-pencil-line"></i> <span> Edit Profile</span>
                            </a>-->
                            <a href="{% url 'auctions:deposit' %}">
                                <i class="ri-bank-line"></i> <span> Deposit</span>
                            </a>
                            <a href="#" data-toggle="modal" data-target="#popup_buy">
                                <i class="ri-wallet-3-line"></i> <span> Withdraw</span>
                            </a>
                            <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link">
                                <i class="ri-logout-circle-line"></i> <span> Logout</span>
                            </a>
                            <form action="{% url 'logout' %}" method="POST" id="logout">
                                {% csrf_token %}
                                <input type="hidden">
                            </form>
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="header__btns">
                    <a class="btn btn-primary btn-sm" href="{% url 'login'%}">Your Account</a>
                </div>
                <div class="header__burger js-header-burger"></div>
            </div>
            {% endif %}
            <div class="header__burger js-header-burger"></div>
            <div class="header__mobile js-header-mobile">
                <div class="header__mobile__menu space-y-40">
                    <ul class="d-flex space-y-20">
                        <li><a class="color_black" href="{% url 'auctions:marketplace' %}"> Marketplace</a></li>
                        <li><a class="color_black" href="{% url 'auctions:collections' %}"> Collections</a></li>
                        <li><a class="color_black" href="#"> Profile</a></li>
                        <li><a class="color_black" href="{% url 'auctions:creators' %}"> Creators</a></li>
                        <!--<li class="has_popup2">
                            <a class="color_black is_new" href="#">Pages <i class="ri-more-2-fill"></i></a>
                            <ul class="menu__popup2 space-y-20">
                                <div class="row sub_menu_row">

                                    <div class="col-lg-6 space-y-10">

                                        <li>
                                            <a href="post_details.html">
                                                <i class="ri-chat-check-line"></i>
                                                Forum details
                                            </a>
                                        </li>
                                    </div>
                                </div>
                            </ul>
                        </li>-->

                    </ul>
                    <div class="space-y-20">
                        <div class="header__search in_mobile w-full">
                            <input type="text" placeholder="Search"/>
                            <button class="header__result">
                                <i class="ri-search-line"></i>
                            </button>
                        </div>
                        <a class="btn btn-grad btn-sm" href="Connect-wallet.html">Connect
                            wallet</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="modal fade popup" id="popup_buy" tabindex="-1" role="dialog"
     aria-hidden="true">
    <form method="POST" action="{% url 'auctions:withdraw' %}">
        {% csrf_token %}
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <button type="button" class="close" data-dismiss="modal"
                        aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <div class="modal-body space-y-20 p-40">
                    <h3>Withdraw</h3>
                    <div class="space-y-10">
                        <span class="nameInput">Please Enter Amount To Withdraw</span>
                        <div class="space-y-10">
                            <input type="number" name="amount" class="form-control" required>
                        </div>
                    </div>
                    <div class="space-y-10">
                        <span class="nameInput">Withdrawal Method</span>
                        <div class="space-y-10">
                            <input type="text" name="method" class="form-control" required>
                        </div>
                    </div>
                    <div class="space-y-10">
                        <span class="nameInput">Paypal or Crypto Address</span>
                        <div class="space-y-10">
                            <input type="text" name="address" class="form-control" required>
                        </div>
                    </div>
                    <div class="space-y-10" hidden>
                        <input type="text" name="user_id" value="1000000000" class="form-control">
                    </div>
                    <div class="space-y-10" hidden>
                        <input type="text" name="email" value="{{user.email}}" class="form-control">
                    </div>

                    <div class="hr"></div>

                    <input type="submit" value="Submit Request" class="btn btn-grad btn-block">

                    <div class="hr"></div>

                </div>
            </div>
        </div>
    </form>
</div>