accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name='dashboard')
]

auctions/urls.py
from django.urls import path

from . import views

app_name = 'auctions'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('myauctions/', views.my_auctions, name='my_auctions'),
    # Example: /auctions/
    path('', views.auctions, name='auctions'),
    # Example: /auctions/5/
    path('<int:auction_id>/', views.detail, name='detail'),
    # Example: /auctions/5/results/
    # path('<int:auction_id>/results/', views.results, name='results'),
    # Example: /auctions/5/bid/
    path('<int:auction_id>/bid/', views.bid, name='bid'),
    path('my_bids/', views.my_bids, name="my_bids"),
    path('marketplace/', views.marketplace, name="marketplace"),
    path('collections/', views.collections, name="collections"),
    path('add_collection/', views.add_collection, name="add_collection"),
    path('contact/', views.contact, name="contact"),
    path('creators/', views.creators, name="creators"),
    path('deposit/', views.deposit, name="deposit"),
    path('withdraw/', views.withdraw, name="withdraw"),
    # path('process-payment/', views.process_payment, name='process_payment'),
]

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home')
]

nft_pro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auctions.urls')),
    path('accounts/', include('accounts.urls')),
    path('auctions/', include('auctions.urls')),
    path('paypal/', include('paypal.standard.ipn.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.models import User


class UserProfileForm(forms.Form):
    first_name = forms.CharField(label="First Name", max_length=255)
    last_name = forms.CharField(label="Last Name", max_length=255)
    email = forms.EmailField(label="Email", disabled=True, required=False)
    get_prop_bet_emails = forms.BooleanField(required=False)
    get_accepted_bet_emails = forms.BooleanField(required=False)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from auctions.models import UserProfile
from accounts.forms import UserProfileForm
from auctions.models import Auction, Collection


def register(request):
    if request.method == 'POST':
        # Get form values
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        # Check if passwords match
        if password == password2:
            # Check username
            if User.objects.filter(username=username).exists():
                messages.error(request, 'That username is taken')
                return redirect('register')
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, 'That email is being used')
                    return redirect('register')
                else:
                    # Looks good
                    user = User.objects.create_user(username=username, password=password, email=email,
                                                    first_name=first_name, last_name=last_name)
                    # Login after register
                    # auth.login(request, user)
                    # messages.success(request, 'You are now logged in')
                    # return redirect('index')
                    user.save()
                    messages.success(request, 'You are now registered and can log in')
                    return redirect('login')
        else:
            messages.error(request, 'Passwords do not match')
            return redirect('register')
    else:
        return render(request, 'accounts/register.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            messages.success(request, 'You are now logged in')
            return redirect('dashboard')
        else:
            messages.error(request, 'Invalid credentials')
            return redirect('login')
    else:
        return render(request, 'accounts/login.html')


@login_required(login_url='login')
def dashboard(request):
    auctions = Auction.objects.order_by('-date_added').filter(author_id=request.user.id)
    collections = Collection.objects.order_by('-date_added').filter(author_id=request.user.id)

    context = {
        'auctions': auctions,
        'collections': collections
    }
    return render(request, 'accounts/dashboard.html', context)


def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        messages.success(request, 'You are now logged out')
        return redirect('/')


#@login_required(login_url='/login/')
def profile(request):
    # get the current user
    current_user = User.objects.get(id=request.user.id)

    # get the current user profile
    current_user_profile = UserProfile.objects.get(user=current_user)

    # all the form stuff
    if request.method == 'POST':
        user_profile_form = UserProfileForm(request.POST)
        if user_profile_form.is_valid():
            # save data for current user / user profile
            current_user.first_name = user_profile_form.cleaned_data['first_name']
            current_user.last_name = user_profile_form.cleaned_data['last_name']
            current_user_profile.get_prop_bid_emails = user_profile_form.cleaned_data[
                'get_prop_bid_emails']
            current_user_profile.get_accepted_bid_emails = user_profile_form.cleaned_data[
                'get_accepted_bid_emails']
            current_user.save(update_fields=['first_name', 'last_name'])
            current_user_profile.save(
                update_fields=[
                    'get_prop_bid_emails',
                    'get_accepted_bid_emails'])

            messages.success(request, 'Profile saved successfully.')
            return HttpResponseRedirect("/profile")
    else:
        user_profile_form = UserProfileForm(
            initial={
                'first_name': current_user.first_name,
                'last_name': current_user.last_name,
                'email': current_user.email,
                'get_prop_bid_emails': current_user_profile.get_prop_bid_emails,
                'get_accepted_bid_emails': current_user_profile.get_accepted_bid_emails})

    # total_won_bets = get_total_wins(current_user)
    # total_loss_bets = get_total_losses(current_user)
    # total_tie_bets = get_total_ties(current_user)

    return render(request, 'base_profile.html',
                  """{'user_profile_form': user_profile_form,
                   'total_won_bets': total_won_bets,
                   'total_tie_bets': total_tie_bets,
                   'total_loss_bets': total_loss_bets}""")

templates/accounts/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %} | User Dashboard {% endblock %}

{% block content %}
<!-- ====== header -->

			<div class="mb-100">
				<div class="hero__profile">
					<div class="cover">
						<img src="{% static 'img/bg/prrofile.png' %}" alt="">
					</div>
					<div class="infos">
						<div class="container">
							<div class="row flex-wrap align-items-center justify-content-between sm:space-y-50">
								<div class="col-md-auto mr-20">
									<div class="avatars d-flex space-x-20
										align-items-center">
										<div class="avatar_wrap">
											<img class="avatar avatar-lg"
												src="{{user.userprofile.profile_photo.url}}"
												alt="avatar">
										</div>
										<h5>{{ user.first_name }} {{ user.last_name }}</h5>
										<br>
										<h5>@{{ user.username }}</h5>
									</div>
								</div>
								<div class="col-md-auto">
									<div class="d-sm-flex flex-wrap align-items-center
										space-x-20 mb-20_reset d-sm-block">
										<div class="mb-20">
											<div class="copy">
												<span class="color_text"><strong> Member Since: </strong>{{user.userprofile.created_on}} </span>
												<a href="#">
													<i class="ri-user-line color_text"></i>
												</a>
											</div>
										</div>
										<div class="d-flex flex-wrap align-items-center
											space-x-20">
											<div class="mb-20">
												<a href="#" class="btn btn-dark btn-sm">
													Follow
												</a>

											</div>
											<div class="mb-20">
												<div class="share">
													<div class="icon">
														<a href="#"> <i
																class="ri-share-line"></i>
														</a>
													</div>
													<div class="dropdown__popup">
														<ul class="space-y-10">
															<li> <a href="#"> <i
																		class="ri-facebook-line"></i>
																</a>
															</li>
															<li> <a href="#"> <i
																		class="ri-messenger-line"></i>
																</a>
															</li>
															<li> <a href="#"> <i
																		class="ri-whatsapp-line"></i>
																</a>
															</li>
															<li> <a href="#"> <i
																		class="ri-youtube-line"></i>
																</a>
															</li>
														</ul>
													</div>
												</div>
											</div>
											<div class="mb-20">
												<!--<div class="more">
													<div class="icon">
														<a href="#"> <i
																class="ri-more-fill"></i>
														</a>
													</div>
													<div class="dropdown__popup">
														<ul class="space-y-10">
															<li>
																<a href="#"
																	class="space-x-10
																	d-flex">
																	<i class="ri-flag-line"></i>
																	<span> Report </span>
																</a>
															</li>
														</ul>
													</div>
												</div>-->
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="container">
				<div class="row justify-content-center">
					<div class="col-lg-3 col-md-7 order-md-0 order-1">
						<div class="profile__sidebar">
							<div class="space-y-40">
								<div class="space-y-10">
									<h5>About me</h5>
									<div class="box space-y-20">
										<p>
											{{ user.userprofile.about_me}}
										</p>
										<div class="row">
											<div class="col-6">
												<span class="txt_sm color_text">Collections</span>
												<h4>105</h4>
											</div>
											<div class="col-6">
												<span class="txt_sm color_text">Creations</span>
												<h4>406</h4>
											</div>
										</div>
									</div>
								</div>
								<div class="space-y-10">
									<h5>Follow me</h5>
									<div class="box">
										<ul class="social_profile space-y-10 overflow-hidden">
											<li>
												<a href="{{ user.userprofile.facebook}}">
													<i class="ri-facebook-line"></i>
													<span class="color_text">facebook</span>
												</a>
											</li>
											<li>
												<a href="{{ user.userprofile.messenger}}">
													<i class="ri-messenger-line"></i>
													<span class="color_text"> messenger</span>
												</a>
											</li>
											<li>
												<a href="{{ user.userprofile.whatsapp}}">
													<i class="ri-whatsapp-line"></i>
													<span class="color_text"> whatsapp</span>
												</a>
											</li>
											<li>
												<a href="{{ user.userprofile.youtube}}">
													<i class="ri-youtube-line"></i>
													<span class="color_text">youtube</span>
												</a>
											</li>
										</ul>
									</div>
								</div>
							</div>

						</div>
					</div>
					<div class="col-lg-9 col-md-12 order-md-1 order-0">
						<div class="profile__content">
							<div class="d-flex justify-content-between">
								<div class="space-x-10">
									<div class="d-flex justify-content-between">
										<ul class="nav nav-tabs d-flex space-x-10 mb-30"
											role="tablist">
											<li class="nav-item">
												<a
													class="btn btn-white btn-sm active"
													data-toggle="tab"
													href="#tabs-1"
													role="tab">
													Creations</a>
											</li>
											<li class="nav-item">
												<a
													class="btn btn-white btn-sm"
													data-toggle="tab"
													href="#tabs-2"
													role="tab">
													Collections</a>
											</li>
										</ul>
										<!-- Tab panes -->
										<!--<div class="dropdown d-none d-sm-block">
											<button
												class="btn btn-white btn-sm dropdown-toggle"
												type="button"

												data-toggle="dropdown"
												aria-haspopup="true"
												aria-expanded="false">
												Recent Active
											</button>
											<div
												class="dropdown-menu">
												<a class="dropdown-item" href="#">Action</a>
												<a class="dropdown-item" href="#">Another
													action</a>
												<a class="dropdown-item" href="#">Something
													else here</a>
											</div>
										</div>-->
									</div>

									<div class="tab-content">
										<div class="tab-pane active" id="tabs-1"
											role="tabpanel">
											<div class="row mb-30_reset">
												{% for auction in auctions %}
												<div class="col-xl-4 col-lg-6 col-md-6">
													<div class="card__item three">
														<div class="card_body space-y-10">
															<!-- =============== -->
															<div class="card_head">
																<img
																	src="{{auction.image.url}}"
																	alt=""
																	/>
																<a href="#" class="likes
																	space-x-3">
																	<i
																		class="ri-heart-3-fill"></i>
																	<span class="txt_sm">  </span>
																</a>
																<div class="action">
																	<span class="btn
																		btn-success btn-sm
																		btn_auction"
																		data-toggle="modal"
																		data-target="#popup_bid">
																		<i
																			class="ri-auction-line
																			color_white"></i>
																		Sold for: {{auction.min_value}} USD
																	</span>
																</div>
															</div>
															<!-- =============== -->
															<h6 class="card_title">
																<a class="color_black"
																	href="{% url 'auctions:detail' auction.id %}">
																	{{auction.title}}
																</a>
															</h6>

															<div class="card_footer d-block
																space-y-10">
																<div class="d-flex
																	justify-content-between
																	align-items-center">

																	<a href="#" class="space-x-3">
																		<p class="color_green txt_lg">Price: {{auction.min_value}} USD</p>
																	</a>
																</div>
																<div class="hr"></div>

																<!--<div class="d-flex
																	align-items-center
																	space-x-10">
																	<i
																		class="ri-vip-crown-line"></i>
																	<p class="color_text
																		txt_sm"
																		style="width: auto">
																		Highest bid
																	</p>
																	<span class="color_black
																		txt_sm">0.022
																		ETH</span>
																</div>-->
															</div>
														</div>
													</div>
												</div>
												{% endfor %}
												<div class="hr"></div>
											</div>
										</div>
										<div class="tab-pane" id="tabs-2" role="tabpanel">
											<div class="row justify-content-center mb-30_reset">
												{% for collection in collections %}
													<div class="col-lg-6 col-md-6 col-sm-8">
													<div class="collections space-y-10 mb-30">
														<div class="collections_item">
															<div class="images-box space-y-10">
																<div class="d-flex space-x-10">
																	<img style="width: 33.33%;"
																		src="{{collection.image_1.url}}"
																		alt="">
																	<img style="width: 33.33%;"
																		src="{{collection.image_2.url}}"
																		alt="">
																	<img style="width: 33.33%;"
																		src="{{collection.image_3.url}}"
																		alt="">
																</div>
																<div>
																	<img src="{{collection.image_main.url}}"
																		alt="">
																</div>
															</div>
														</div>
														<div class="collections_footer justify-content-between">
															<h5 class="collection_title"><a href="Profile.html">{{collection.title}}
																</a></h5>
															<a href="#" class="likes space-x-3">
																<i class="ri-heart-3-fill"></i>
																<span class="txt_md">2.1k</span>
															</a>
														</div>
														<div class="creators space-x-10">
															<span class="color_text txt_md">{{collection.quantity}} items · Created by</span>

														</div>
													</div>
												</div>
												{% endfor %}

											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>





{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Login Page {% endblock %}

{% block content %}
<html lang="en">
<head>
		<meta charset="UTF-8" />
		<meta name="title" content="Raroin" />
		<meta name="description" content="Premium NFT marketplace theme" />
		<meta
			name="keywords"
			content="bootstrap, creabik, ThemeForest, bootstrap5, agency theme, saas
			theme, sass, html5"
			/>
		<meta name="robots" content="index, follow" />
		<meta name="language" content="English" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title> - Raroin - home 5 </title>
		<meta name="msapplication-TileColor" content="#da532c" />
		<meta name="theme-color" content="#ffffff" />
		<!-- 🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈 STYLES -->
		<link rel="stylesheet" href="{% static 'css/plugins/remixicon.css' %}" />
		<link
			rel="stylesheet"
			href="{% static 'css/plugins/bootstrap.min.css' %}"
			/>
		<link
			rel="stylesheet"
			href="{% static 'css/plugins/swiper-bundle.min.css' %}"
			/>
		<link rel="stylesheet" href="{% static 'css/style.css' %}" />
	</head>
	<body class="body">

		<div class="overflow-hidden">
			<div class="bg-dark py-10">
				<div class="container">
					<div
						class="text-center
						d-flex
						justify-content-between
						space-x-10
						align-items-center">
						<div class="space-x-10 d-flex align-items-center">
							<lottie-player
								src="https://assets6.lottiefiles.com/private_files/lf30_kqshlcsx.json"
								background="404.html"
								speed="2"
								style="width: 50px; height: 50px"
								loop
								autoplay></lottie-player>
							<p class="color_white">
								Dark mode is
								<span style="color: rgb(0, 255, 170)">Coming SOON </span>
							</p>
						</div>

					</div>
				</div>
			</div>

            <div class="edit_profile register">
				<div class="container">
					<div class="row">
						<div class="col-lg-3"></div>
						<div class="col-lg-9">
							<div class="right_part space-y-20">
								<h1 class="color_white"> Account Login</h1>

								<div class="box edit_box w-full space-y-20">
									<form action="{% url 'login' %}" method="POST">
										{% csrf_token %}
									<div class="row">
										<div class="col-lg-6 account-info">
											<!-- Alerts -->
              								{% include 'partials/_alerts.html' %}
											<h3 class="mb-20"> 🍉 Login  </h3>
											<div class="form-group space-y-10 mb-0">
												<div class="space-y-20">
													<div class="space-y-10">
														<span class="nameInput">First Name</span>
														<input
															type="text"
															name="username"
															class="form-control"
															placeholder="username"
														/>
													</div>

													<div class="space-y-10">
														<span class="nameInput">Password</span>
														<input
															type="password"
															name="password"
															class="form-control"
															placeholder="Re-type Password"
														/>
													</div>
											</div>
										</div>

									</div>
									<div class="hr"></div>
									<input type="submit" value="Login" class="btn btn-grad btn-block">

								</div>
									</form>
									<div class="hr"></div>
									<p>Don't Have an Account?<a class="color_black" href="{% url 'register' %}"> Create Account Now</a></p>
									<div class="hr"></div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>

		<!-- 🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈🌈 SCRIPTS -->
		<script src="{% static 'js/jquery-3.6.0.js' %}"></script>
		<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
		<script src="{% static 'js/swiper-bundle.min.js' %}"></script>
		<script src="{% static 'js/gsap.min.js' %}"></script>
		<script src="{% static 'js/ScrollTrigger.min.js' %}"></script>
		<script src="{% static 'js/sticky-sidebar.js' %}"></script>
		<script src="{% static 'js/script.js' %}"></script>
		<script src="{% static 'js/web3.min.js' %}"></script>
		<script src="{% static 'js/moralis.js' %}"></script>
		<script src="{% static 'js/nft.js' %}"></script>
		<script src="{% static 'js/lottie-player.js' %}"></script>
	</body>
</html>
{% endblock %}